#!/bin/sh
set -e

if [ ! -z "$GET_DBEUG" ]; then
  set -vx
fi

TAR_FILE="/tmp/variant.tar.gz"
RELEASES_URL="https://github.com/mumoshu/variant/releases"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
TMPDIR=${TMPDIR%%/}

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" | 
    rev | 
    cut -f1 -d'/'| 
    rev
}

download() {
  test -z "$VERSION" && VERSION="$(last_version)"
  test -z "$VERSION" && {
    echo "Unable to get variant version." >&2
    exit 1
  }
  version=$VERSION
  version=${version#v}
  os=$(uname -s)
  os=${os/Linux/linux}
  os=${os/Darwin/darwin}
  arch=$(uname -m)
  arch=${arch/x86_/amd}
  arch=${arch/i386/386}
  url="$RELEASES_URL/download/${VERSION}/variant_${version}_${os}_${arch}.tar.gz"
  rm -f "$TAR_FILE"
  curl -s -L -o "$TAR_FILE" "$url" || echo "failed downloading $url"
}

download
tar -xf "$TAR_FILE" -C "$TMPDIR"

if [ ! -z "$INSTALL_TO" ]; then
  echo "Installing variant to ${INSTALL_TO}..." 1>&2
  mv "${TMPDIR}/variant" "$INSTALL_TO"
  echo "Done!" 1>&2
else
  "${TMPDIR}/variant" "$@"
fi
